eval_folder: diff_combined_reg
notes: reg
triplet_mode: diff_content
data_path: data/2_7/facebook_react

code_df_cache: data/merged_code_df/multi_code_df.parquet
index_path: "${data_path}/index_commit_tokenized"
k: 1000
n: 100
model_path: microsoft/codebert-base
batch_size: 32
num_epochs: 20
learning_rate: 5e-5
num_positives: 10
num_negatives: 10
train_depth: 1000
num_workers: 8
train_commits: 1500
psg_cnt: 25
psg_len: 350
psg_stride: 250
aggregation_strategy: maxp
rerank_depth: 100
openai_model: gpt4
bert_best_model: data/combined_commit_train/best_model
train_mode: regression